application:
  title: School Census
  version: 0.0.1

server:
  port: 8080
  servlet:
    context-path: /school-census/api
  tomcat:
    max-max-swallow-size: 100MB

spring:
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
    show-sql: true
  datasource:
    driverClassName: org.postgresql.Driver
    platform: postgres
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 300MB

client:
  name: MachineLearningModel
  url: http://localhost:5000
